spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/online_catering_db
spring.datasource.username=catering_user
spring.datasource.password=catering_password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=nqafitXu6hRJeOeSuIG8jmijh4k9B3GopgYXES/6e7E=
jwt.expiration=86400000
server.port=8080
cloudinary.cloud_name=dmfxi6upt
cloudinary.api_key=625279343338174
cloudinary.api_secret=mLQeTrp1ligHjmwS6OA3dmOCbhU

logging.level.org.springframework.security=DEBUG


spring.mail.host=smtp.sendgrid.net
spring.mail.port=587
spring.mail.username=apikey
spring.mail.password=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
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.starttls.required=true
#spring.mail.default-encoding=UTF-8